//
//  SearchRouter.swift
//  Music player
//
//  Created by Виталий Сосин on 20.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchRoutingLogic {

}

class SearchRouter: NSObject, SearchRoutingLogic {

  weak var viewController: SearchViewController?
  
  // MARK: Routing
  
}
